--CONFIGURAR PARAMETROS BASE DE DATOS
--SGA
SHOW PARAMETERS SGA;
ALTER SYSTEM SET SGA_TARGET=500M scope=spfile;
--Sessions formula Default value Derived: (1.5 * PROCESSES) + 22
SHOW PARAMETER sessions;
ALTER SYSTEM SET sessions=500 scope=spfile
--Processes 
SHOW PARAMETERS processes;
ALTER SYSTEM SET processes=1500 scope=spfile; 
--PGA
SHOW PARAMETERS PGA;
ALTER SYSTEM SET pga_aggregate_target=100M scope=spfile;
--COMANDOS PARA REINICIAR LA BD solo admin puede
shutdown immediate 
startup
--------------------
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
--CREACION TABLESPACE ZAPATERIA
CREATE USER ZAPATERIA IDENTIFIED BY zapa;
CREATE TABLESPACE TSZAPATERIA DATAFILE 'ZAPATERIADF.tbs' SIZE 250M
      AUTOEXTEND on maxsize 500M;
      
      
ALTER USER ZAPATERIA DEFAULT TABLESPACE TSZAPATERIA;
SELECT * FROM DBA_USERS;
-- VER INFO TABLESPACE O ELIMINARLO
DROP TABLESPACE TSZAPATERIA INCLUDING CONTENTS AND DATAFILES;
SELECT * FROM DBA_TABLESPACES;

-- CREACION DE ROLES--
CREATE ROLE Contabilidad;
CREATE ROLE Ventas;
CREATE ROLE IT;
CREATE ROLE Gerencia;

--ASIGNAR PERMISOS A LOS ROLES

--PERMISOS ROL Contabilidad;
GRANT INSERT TABLE TO Contabilidad;
GRANT SELECT TABLE TO Contabilidad;
GRANT CONNECT TO Contabilidad;

--PERMISOS ROL Ventas;
GRANT INSERT TABLE TO Ventas;
GRANT SELECT TABLE TO Ventas;
GRANT CONNECT TO Ventas;

--PERMISOS ROL IT;
GRANT SELECT TABLE TO IT;
GRANT DELETE TABLE TO IT;
GRANT CREATE USER TO IT;
GRANT CREATE TABLE TO IT;
GRANT CONNECT TO IT;

--PERMISOS ROL Gerencia;
GRANT UPDATE TO Gerencia;
GRANT INSERT TO Gerencia;
GRANT SELECT TO Gerencia;
GRANT DELETE TO Gerencia;
GRANT CREATE USER TO Gerencia;
GRANT CONNECT TO Gerencia;


--CREAR USUARIOS Y ASIGNACION DE ROLES
CREATE USER Contabilidad1 IDENTIFIED BY bd2Conta1 ;
CREATE USER Contabilidad2 IDENTIFIED BY Contabilidad2 ;
GRANT Contabilidad TO Contabilidad1;
GRANT Contabilidad TO Contabilidad2;


CREATE USER Ventas1 IDENTIFIED BY bd2Ventas1;
CREATE USER Ventas2 IDENTIFIED BY bd2Ventas2;
GRANT Ventas TO Ventas1;
GRANT Ventas TO Ventas1;

CREATE USER IT1 IDENTIFIED BY bd2IT1;
CREATE USER IT2 IDENTIFIED BY bd2IT2;
GRANT IT TO IT1;
GRANT IT TO IT2;

CREATE USER Gerencia1 IDENTIFIED BY bd2Gerencia1;
CREATE USER Gerencia2 IDENTIFIED BY bd2Gerencia2;
GRANT Gerencia TO Gerencia1;
GRANT Gerencia TO Gerencia2;

