-- CANTIDAD DE FACTURAS
EXPLAIN PLAN FOR
SELECT  (select cliente.nombre_cliente from cliente where id_cliente = c.id_cliente) AS NOMBRE,
count(c.id_cliente) AS CANTIDAD 
from factura f inner join cliente c on f.id_cliente = c.id_cliente 
group by c.id_cliente;

CREATE INDEX indice1 on factura(id_cliente);
DROP INDEX indice1;

-- SOLUCION CON SUBCONSULTA TOP3

EXPLAIN PLAN FOR SELECT (SELECT PR.NOMBRE_PRODUCTO FROM PRODUCTO PR WHERE PR.ID_PRODUCTO = D.ID_PRODUCTO), 
SUM(D.CANTIDAD) AS CANTIDAD 
FROM DETALLE D,PRODUCTO P 
WHERE D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO
ORDER BY CANTIDAD DESC
FETCH FIRST 3 ROWS ONLY;

CREATE INDEX indice2 on detalle(id_factura);
DROP INDEX indice2;

-- SOLUCION CON SUBCONSULTA TOP5
EXPLAIN PLAN FOR SELECT (select PRODUCTO.NOMBRE_PRODUCTO from PRODUCTO where PRODUCTO.ID_PRODUCTO = D.ID_PRODUCTO) AS NOMBRE,  
SUM(D.CANTIDAD) AS CANTIDAD 
from DETALLE D inner join PRODUCTO P on D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD ASC
FETCH FIRST 5 ROWS ONLY;

CREATE INDEX indice3 on producto(nombre_producto);
DROP INDEX indice3;


-- CREAR VISTA TOP3 VENTA

CREATE VIEW TOP3VENTA AS 
SELECT (select PRODUCTO.NOMBRE_PRODUCTO from PRODUCTO where PRODUCTO.ID_PRODUCTO = D.ID_PRODUCTO) AS NOMBRE,  
SUM(D.CANTIDAD) AS CANTIDAD 
from DETALLE D inner join PRODUCTO P on D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD DESC
FETCH FIRST 3 ROWS ONLY;


-- CREAR VISTA TOP 5 MENNOS VENTA
CREATE VIEW TOP5VENTA AS 
SELECT (select PRODUCTO.NOMBRE_PRODUCTO from PRODUCTO where PRODUCTO.ID_PRODUCTO = D.ID_PRODUCTO) AS NOMBRE,  
SUM(D.CANTIDAD) AS CANTIDAD 
from DETALLE D inner join PRODUCTO P on D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD ASC
FETCH FIRST 5 ROWS ONLY;


-- REALIZAR TRACE Y TKPROF MANUAL

-- Cambiar el nombre de tracefile
alter session set tracefile_identifier='TOP3PRODUCTO';

-- Habilidar Trace
BEGIN DBMS_SESSION.SESSION_TRACE_ENABLE; end;

-- Realizar la consulta
SELECT (SELECT PR.NOMBRE_PRODUCTO FROM PRODUCTO PR WHERE PR.ID_PRODUCTO = D.ID_PRODUCTO), 
SUM(D.CANTIDAD) AS CANTIDAD 
FROM DETALLE D,PRODUCTO P 
WHERE D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO
ORDER BY CANTIDAD DESC
FETCH FIRST 3 ROWS ONLY;

-- Desabilitar trace
BEGIN DBMS_SESSION.SESSION_TRACE_DISABLE; end;

-- Verificar informacion del plan de ejecucion de la consulta
SELECT * FROM V$DIAG_INFO;

--- ruta donde se guarda 
/u01/app/oracle/diag/rdbms/orcl18/ORCL18/trace


-- Comando para traducir el con la herramienta de tkprof
tkprof ORCL18_ora_541_TOP3PRODUCTO.trc /u01/app/oracle/salidaTOP3.txt

-- Ruta con nombre del archivo en donde se hizo la traduccion con la herramienta tkprof
/u01/app/oracle/salidaTOP3.txt
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD ASC
FETCH FIRST 5 ROWS ONLY;

-- Consulta con explain
EXPLAIN PLAN FOR 
SELECT (select PRODUCTO.NOMBRE_PRODUCTO from PRODUCTO where PRODUCTO.ID_PRODUCTO = D.ID_PRODUCTO) AS NOMBRE,  
SUM(D.CANTIDAD) AS CANTIDAD 
from DETALLE D inner join PRODUCTO P on D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD ASC
FETCH FIRST 5 ROWS ONLY;


-- VER VISTA Y BORRAR VISTA TOP3

SELECT * FROM TOP3VENTA;
DROP VIEW TOP3VENTA;

-- VER VISTA Y BORRAR VISTA TOP5
SELECT * FROM TOP5VENTA;
DROP VIEW TOP5VENTA;

-- Verificar plan de ejecucion con explain

SELECT* FROM TABLE(dbms_xplan.display);
