
-- SOLUCION CON SUBCONSULTA TOP3

EXPLAIN PLAN FOR SELECT (SELECT PR.NOMBRE_PRODUCTO FROM PRODUCTO PR WHERE PR.ID_PRODUCTO = D.ID_PRODUCTO), 
SUM(D.CANTIDAD) AS CANTIDAD 
FROM DETALLE D,PRODUCTO P 
WHERE D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO
ORDER BY CANTIDAD DESC
FETCH FIRST 3 ROWS ONLY;


-- CREAR VISTA TOP3 VENTA

CREATE VIEW TOP3VENTA AS 
SELECT (select PRODUCTO.NOMBRE_PRODUCTO from PRODUCTO where PRODUCTO.ID_PRODUCTO = D.ID_PRODUCTO) AS NOMBRE,  
SUM(D.CANTIDAD) AS CANTIDAD 
from DETALLE D inner join PRODUCTO P on D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD DESC
FETCH FIRST 3 ROWS ONLY;


-- CREAR VISTA TOP 5 MENNOS VENTA
CREATE VIEW TOP5VENTA AS 
SELECT (select PRODUCTO.NOMBRE_PRODUCTO from PRODUCTO where PRODUCTO.ID_PRODUCTO = D.ID_PRODUCTO) AS NOMBRE,  
SUM(D.CANTIDAD) AS CANTIDAD 
from DETALLE D inner join PRODUCTO P on D.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY D.ID_PRODUCTO 
ORDER BY CANTIDAD ASC
FETCH FIRST 5 ROWS ONLY;


-- VER VISTA Y BORRAR VISTA TOP3

SELECT * FROM TOP3VENTA;
DROP VIEW TOP3VENTA;

-- VER VISTA Y BORRAR VISTA TOP5
SELECT * FROM TOP5VENTA;
DROP VIEW TOP5VENTA;